version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      DATABASE_USER: ${DOCKER_DATABASE_USER}
      DATABASE_NAME: ${DOCKER_DATABASE_NAME}
      DATABASE_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_USER: ${DOCKER_DATABASE_USER}
      POSTGRES_NAME: ${DOCKER_DATABASE_NAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${DOCKER_DATABASE_HOST_AUTH_METHOD}