version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:18.17.0
jobs:
  test:

    executor: my-custom-executor
    steps:
      - setup_remote_docker:
          version: docker24
      - checkout
      - run:
          name: update-npm
          command: "npm install -g npm@latest"

workflows:
  my-custom-workflow:
    jobs:
      - test