/* eslint-disable comma-dangle */
import { QueryInterface } from "sequelize";
import { hashPassword } from "../../helpers";
import {
  userOneId,
  userTwoId,
  userThreeId,
  userFourId,
  userFiveId,
  userSixId,
  userSevenId,
  userEightId,
  userNineId,
  userTenId,
  userElevenId,
  userTwelveId,
  userThirteenId,
  userFourTeenId,
  userFiveTeenId,
} from "../../types/uuid";

const userOne = {
  id: userOneId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Admin",
  lastName: "L Admin",
  email: "ecommerceninjas45@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "admin",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};
const userTwo = {
  id: userTwoId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Buyer",
  lastName: "L Buyer",
  email: "buyer@gmail.com",
  password: hashPassword("Password@123"),
  phone: 1234567890,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "1990-01-01",
  language: "English",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userThree = {
  id: userThreeId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Buyer1",
  lastName: "L Buyer1",
  email: "buyer1@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: true,
};

const userFour = {
  id: userFourId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Seller",
  lastName: "L Seller",
  email: "aimegetz@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767099,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userFive = {
  id: userFiveId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "dj5090",
  lastName: "dj2090",
  email: "jadowacu@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2014-02-02",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userSix = {
  id: userSixId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Seller3",
  lastName: "L Seller3",
  email: "ndahimana154@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2014-02-02",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userSeven = {
  id: userSevenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Seller4",
  lastName: "L Seller4",
  email: "ijbapte@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2014-02-02",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userEight = {
  id: userEightId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Buyer2",
  lastName: "L Buyer2",
  email: "buyer2@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767809,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};
const userNine = {
  id: userNineId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "IR Buyer2",
  lastName: "U Buyer2",
  email: "invalidroleuser@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767809,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "nurse",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userTen = {
  id: userTenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date("2020-01-01T12:00:00Z"),
  firstName: "Aime",
  lastName: "Patrick",
  email: "aimepatrick64@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};
const userEleven = {
  id: userElevenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Buyer3",
  lastName: "L Buyer3",
  email: "buyer4@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userTwelve = {
  id: userTwelveId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "New",
  lastName: "Admin",
  email: "newadmin@gmail.com",
  password: hashPassword("AdminPassword@123"),
  phone: 25089767999,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "1-1-1980",
  language: "english",
  currency: "USD",
  role: "admin",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userThirteen = {
  id: userThirteenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "Ecommerce",
  lastName: "Ninjas",
  email: "ecommerceninjas@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767999,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "1-1-1980",
  language: "english",
  currency: "USD",
  role: "buyer",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false
};
const userFourteen = {
  id: userFourTeenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Seller14",
  lastName: "L Seller14",
  email: "seller14@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767899,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "female",
  birthDate: "2014-02-02",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

const userFiveTeen = {
  id: userFiveTeenId,
  createdAt: new Date(),
  updatedAt: new Date(),
  passwordUpdatedAt: new Date(),
  firstName: "F Seller",
  lastName: "L Seller",
  email: "seller15@gmail.com",
  password: hashPassword("Password@123"),
  phone: 25089767099,
  profilePicture: "https://res.cloudinary.com/djrmfg6k9/image/upload/v1720294521/cce1ffu7uw3j2vg9s2vl.jpg",
  gender: "male",
  birthDate: "2-2-2014",
  language: "english",
  currency: "USD",
  role: "seller",
  status: "enabled",
  isVerified: true,
  is2FAEnabled: false,
};

export const up = (queryInterface: QueryInterface) =>
  queryInterface.bulkInsert("users", [
    userOne,
    userTwo,
    userThree,
    userFour,
    userFive,
    userSix,
    userSeven,
    userEight,
    userNine,
    userTen,
    userEleven,
    userTwelve,
    userThirteen,
    userFourteen,
    userFiveTeen
  ]);

export const down = async (queryInterface: QueryInterface) => {
  await queryInterface.bulkDelete("users", {});
};
